env:
  browser: true
  es2021: true
extends:
  - react-app
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
settings:
  react:
    version: "detect"
rules: {}
