name: Pylint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: python -m pylint RepoToText.py FolderToText.py
